### ISSUE TITLE
移动端点击事件位置偏移

### ISSUE THREAD

**Issue by ZSLOGIN** [ferrinweb/voice-input-button2#11]
在谷歌浏览器上调试移动端模式，按钮的点击事件会发生偏移，点按钮正中不行，大概在按钮外右侧一点点点击才会触发，并且控制台会报“Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.”这个错误，想问下这个是怎么回事？新手不太懂，恳请指点^_^

**Comment by ferrinweb** [comment]
打开移动模式后，刷新下页面试试。另外检查下是否有祖先元素绑定了 touchstart 事件。

**Comment by ZSLOGIN** [comment]
touch cancelable 是已经解决了，在voice-input-button.js文件里的 e.preventDefault(); 前加了条件 e.cancelable && e.preventDefault();
但是移动端点击事件点击中间的麦克风图标是没反应的，要点及它的四周，点四周也不是100%触发，我已经将这个组件拎到了一个单独的页面，如果切换成电脑端的调试点击没有任何问题，但就是切换到移动端的调试点击不太可以

**Comment by ZSLOGIN** [comment]
> 另请检查下是否有祖先元素绑定了touchstart事件。

touch cancelable是已经解决了，在voice-input-button.js文件里的e.preventDefault（）; 前加了条件e.cancelable && e.preventDefault（）;
目前也没有看到有其他元素有touchstart事件
但是移动端点击事件点击中间的麦克风图标是没反应的，要点及它的周围，点周围也不是100％触发，我已经将这个组件拎到了一个单独的页面，如果切换成电脑端的调试点击没有任何问题，但就是切换到移动端的调试点击不太可能

**Comment by ferrinweb** [comment]
已修复。
