### ISSUE TITLE
识别速度偏慢

### ISSUE THREAD

**Issue by haoyunyan** [ferrinweb/voice-input-button2#12]
等待几秒后才会显示结果，看官方的识别速度蛮快的。请问还需要单独配置什么嘛，谢谢

**Comment by ferrinweb** [comment]
识别速度慢可能是网络原因，打开浏览器开发工具，切到网络面板，看下请求速度如何。

另外这个组件支持“增量”“完整”两种识别结果返回模式，在完整模式下需要全部说完后一次性返回识别的结果，可能感官上会觉得比较慢。这个模式通过 `returnMode` 属性配置。

**Comment by haoyunyan** [comment]
返回模式都试过了，看了下应该是wss://iat-api.xfyun.cn/v2/iat时间太长导致的。另外把vad_eos设置小了。
谢谢啦
