### ISSUE TITLE
无法录音：未找到录音设备、当前浏览器不支持录音或用户未授权！

### ISSUE THREAD

**Issue by HQiHang** [ferrinweb/voice-input-button2#14]
为什么使用的时候会弹出
无法录音：未找到录音设备、当前浏览器不支持录音或用户未授权！
这个错误呢

**Comment by ferrinweb** [comment]
如果是使用在浏览器环境下，需要系统赋予浏览器录音权限。如果未赋予或无法赋予其录音权限，则会给出上述提示。

**Comment by HQiHang** [comment]
> 如果是使用在浏览器环境下，需要系统赋予浏览器录音权限。如果未赋予或无法赋予其录音权限，则会给出上述提示。

运行讯飞提供的jsdemo就可以运行并且可以进行语音识别，但是用这个就不可以。

**Comment by ferrinweb** [comment]
好，麻烦贴下讯飞 jsdemo 的地址，我测试下

**Comment by HQiHang** [comment]
> 好，麻烦贴下讯飞 jsdemo 的地址，我测试下

我把地址换成localhost就可以了，之前用本机地址就不行。我再研究一下吧，谢谢哈！

**Comment by ferrinweb** [comment]
不客气。
