### ISSUE TITLE
ios系统无法正常使用 提示 无法录音：未找到录音设备、当前浏览器不支持录音或用户未授权！

### ISSUE THREAD

**Issue by wlor0623** [ferrinweb/voice-input-button2#15]
启用了https 应该能使用麦克风才对 设置也都启用了权限 安卓端可以使用 ios系统好像不行? 控制台也没有报错

**Comment by wlor0623** [comment]
看了下源码可能是`start`方法没有判断浏览器是否支持`Navigator.mediaDevices.getUserMedia()` 导致的不兼容问题
新型浏览器应当使用 `Navigator.mediaDevices.getUserMedia()` 替代`navigator.getUserMedia()` 

[navigator.getUserMedia()](https://developer.mozilla.org/zh-CN/docs/Web/API/MediaDevices/getUserMedia)

**Comment by ferrinweb** [comment]
好，可能是这个原因，我调试下，同时，欢迎PR
