### ISSUE TITLE
vue中如何模拟点击？

### ISSUE THREAD

**Issue by tracyzhao2018** [ferrinweb/voice-input-button2#18]
我写上this.$refs.refName(给此插件voice-input-button标签加上ref).$el.click()；没有用，也不报错

**Comment by ferrinweb** [comment]
接受点击（touch or click）事件的元素是按钮，不是该组件外壳。另外在某些场景下，比如自动全屏、录音可能会有限制，浏览器限制须是真人触发事件，即模拟触发事件可能不起作用。

**Comment by ferrinweb** [comment]
我先关闭了，如果有需要可再次打开。

**Comment by tracyzhao2018** [comment]
没找到这个.record-btn

**Comment by tracyzhao2018** [comment]
找到了.record-btn 但是还是无法触发。悲剧啊
