### ISSUE TITLE
报这个错

### ISSUE THREAD

**Issue by zhangxiaowai** [ferrinweb/voice-input-button2#19]
* ./lib/voice-input-button in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Home.vue?vue&type=script&lang=js&

**Comment by ferrinweb** [comment]
工程目录文件完整吗？发个报错的完整栈截图

**Comment by ferrinweb** [comment]
我先关闭了，如有问题请再次打开
