### ISSUE TITLE
引入worker报错了

### ISSUE THREAD

**Issue by yaojin2070** [ferrinweb/voice-input-button2#2]
![image](https://user-images.githubusercontent.com/48686959/71389472-7e2a9c80-2637-11ea-9734-4375ea820e47.png)
![image](https://user-images.githubusercontent.com/48686959/71389487-900c3f80-2637-11ea-9342-31a67ed6abac.png)
好像是说array.from没有定义,不知道怎么解决,我是将你的demo换成实时语音的,不是语音听写的,各种百度谷歌都找不到答案,困扰了我好久

**Comment by ferrinweb** [comment]
babel 核心不支持 Array.from, 需要安装依赖 babel-polyfill：
`yarn add -D babel-polyfill`
或者
`npm install -D babel-polyfill`

然后找到 webpack.config.js, 修改入口配置：
`entry: process.env.NODE_ENV === 'production' ? ['babel-polyfill', './src/lib/index.js'] : ['babel-polyfill', './src/main.js']`
