### ISSUE TITLE
发现源码里面没有动态判断ws还是wss   

### ISSUE THREAD

**Issue by 2410024100** [ferrinweb/voice-input-button2#21]
connectWebsocket () {
    const url = 'wss://iat-api.xfyun.cn/v2/iat'
 。。。。。。

希望作者加下判断哈。。。测试环境是http。。。正式环境才是https   QQ:2410024100

**Comment by 2410024100** [comment]
var ishttps = 'https:' == location.protocol ? true: false;
    const url = ishttps?'wss://iat-api.xfyun.cn/v2/iat':'ws://iat-api.xfyun.cn/v2/iat'

到时加了。。。我再拉哈   哈哈

**Comment by ferrinweb** [comment]
这个需要你自己处理下。
