### ISSUE TITLE
能否加一个延时的参数

### ISSUE THREAD

**Issue by tracyzhao2018** [ferrinweb/voice-input-button2#22]
点击时我希望等待几秒后执行开始录音的效果。因为本屌丝的老板需求是需要在录音执行前播放一段语音播报

**Comment by ferrinweb** [comment]
这个需求应该很明确不属于这个组件功能范畴，可能需要外部解决。
比如由一个不可见浮层按钮来控制操作，播放完语音后，通过 ref 调用该组件内部的启动方法，启动方法在 `src/lib/voice-input-button.vue` line:79。你会发现启动方法有事件处理，因此需要模拟一个事件参数 `e`。

> 如果你也认为 Boss 的需求有问题，可以考虑下换个方式实现需求。

**Comment by tracyzhao2018** [comment]
> 这个需求应该很明确不属于这个组件功能范畴，可能需要外部解决。
> 比如由一个不可见浮层按钮来控制操作，播放完语音后，通过 ref 调用该组件内部的启动方法，启动方法在 `src/lib/voice-input-button.vue` line:79。你会发现启动方法有事件处理，因此需要模拟一个事件参数 `e`。
> 
> > 如果你也认为 Boss 的需求有问题，可以考虑下换个方式实现需求。

感谢作者回复，您的插件在我项目的node_modules库中，我该如何操作您插件的dom？我就想用您的插件，感觉挺好的。非常感谢作者的辛勤付出。

**Comment by tracyzhao2018** [comment]
> > 这个需求应该很明确不属于这个组件功能范畴，可能需要外部解决。
> > 比如由一个不可见浮层按钮来控制操作，播放完语音后，通过 ref 调用该组件内部的启动方法，启动方法在 `src/lib/voice-input-button.vue` line:79。你会发现启动方法有事件处理，因此需要模拟一个事件参数 `e`。
> > > 如果你也认为 Boss 的需求有问题，可以考虑下换个方式实现需求。
> 
> 感谢作者回复，您的插件在我项目的node_modules库中，我该如何操作您插件的dom？我就想用您的插件，感觉挺好的。非常感谢作者的辛勤付出。

我发现可以把您的插件放在我项目components组件中引用使用吧？但是我在组件方法中例如start中写个console并没有执行。求解惑

**Comment by ferrinweb** [comment]
使用方式与其他组件一致，定义一个 ref 引用名称，通过 `this.$refs.refName` 引用组件实例。
关于未如期产生调试输出的问题，可能你需要在 start 调用之前打个 `debugger`，调试看看。
