### ISSUE TITLE
为何单独从源码里面检出来， 一直识别不出来呢。。也不报错

### ISSUE THREAD

**Issue by 2410024100** [ferrinweb/voice-input-button2#23]
我放到了我项目里面，当成组件调用

**Comment by 2410024100** [comment]
有时会报错：
6f07efde-650f-49c0-b92d-8975d21daf5d:46 Uncaught ReferenceError: __WEBPACK_IMPORTED_MODULE_0_babel_runtime_core_js_array_from___default is not defined
    at Object.to16BitPCM (6f07efde-650f-49c0-b92d-8975d21daf5d:46)
    at Object.transaction (6f07efde-650f-49c0-b92d-8975d21daf5d:17)
    at onmessage (6f07efde-650f-49c0-b92d-8975d21daf5d:9)

**Comment by ferrinweb** [comment]
应该是开发环境依赖版本不匹配造成的

**Comment by 2410024100** [comment]
报错跟这个问题是一样的。。。虽然我是语音听写。。。我试试看。谢谢大佬
https://github.com/ferrinweb/voice-input-button2/issues/2

**Comment by 2410024100** [comment]
问下大佬。。。在内嵌在钉钉app 里面打开网页。。就获取不到录音设备。。无法录音。是怎么回事呢。。。其他端目前是正常

**Comment by ferrinweb** [comment]
这个需要看钉钉App中的webview是否支持第三方页面录音了

**Comment by 2410024100** [comment]
> 这个需要看钉钉App中的webview是否支持第三方页面录音了

好的，谢谢大佬回复。。。。目前还是直接用了大佬的插件引入。  封装成自己的组件会报错。。也不知道什么问题。

**Comment by 2410024100** [comment]
`import locales from './locales.json'
const defaultConfig = {

  color: '#333',
  tipPosition: 'top',
  tipTextColor: '#f2f2f2',
  tipBackgroundColor: '#4b667d',
  tipShadowColor: 'rgba(0,0,0,.1)',
  interactiveMode: 'press',
  returnMode: 'increment',
  language: 'zh_cn',
  vad_eos: 3000
}
export default {
  props: {

    tipTextColor: String,  // 这里算一个
    tipBackgroundColor:  String,   // 这里算一个
    tipShadowColor:  String,    // 这里算一个
 
    color: String,
    tipPosition: String,
   ........
  },`

对了，有个问题跟大佬汇报下。。。mixins混合里面，我发现有几个属性不会生效，要写在在props里才生效

**Comment by ferrinweb** [comment]
谢谢反馈，我闲下来检查下

**Comment by liuyvhang** [comment]
问下大佬，在edge下worker的postMessage无效，请问怎么解决？

**Comment by zhaoxiaozhao1** [comment]
Error in created hook: "TypeError: Cannot read property 'getUserMedia' of undefined"
这是什么为什么呀

**Comment by ferrinweb** [comment]
> Error in created hook: "TypeError: Cannot read property 'getUserMedia' of undefined"
> 这是什么为什么呀

参考是不是这个原因：#24

**Comment by zhaoxiaozhao1** [comment]
ok，谢谢

> > 创建的挂钩中出现错误：“ TypeError：无法读取未定义的属性'getUserMedia'” 
> > 这是什么为什么呀
> 
> 参考是不是这个原因：[＃24](https://github.com/ferrinweb/voice-input-button2/issues/24)
ok，谢谢

**Comment by zhaoxiaozhao1** [comment]
问一下，在node_modules里边修改了voice-input-button.vue文件， 项目npm run dev 后，修改的内容没有体现出来需要怎么搞啊？谢谢哦

**Comment by ferrinweb** [comment]
默认引用的是 `dist/voice-input-button.js` 文件。如果需要直接引用组件，则使用 `import voiceInputButton from 'voice-input-button2/src/lib'`。

**Comment by zhaoxiaozhao1** [comment]
> 默认引用的是 `dist/voice-input-button.js` 文件。如果需要直接引用组件，则使用 `import voiceInputButton from 'voice-input-button2/src/lib'`。

好的

**Comment by upholdjx** [comment]
![image](https://user-images.githubusercontent.com/18349638/94017748-5fce1900-fde2-11ea-9870-3374f178ad0f.png)

HTTP Authentication failed; no valid credentials available

npm 安装了填写了key相关的一点击录音就报这个错

**Comment by ferrinweb** [comment]
验证失败，检查鉴权配置。

**Comment by keke195** [comment]
> 有时会报错： 6f07efde-650f-49c0-b92d-8975d21daf5d:46 Uncaught ReferenceError: __WEBPACK_IMPORTED_MODULE_0_babel_runtime_core_js_array_from___default is not defined at Object.to16BitPCM (6f07efde-650f-49c0-b92d-8975d21daf5d:46) at Object.transaction (6f07efde-650f-49c0-b92d-8975d21daf5d:17) at onmessage (6f07efde-650f-49c0-b92d-8975d21daf5d:9)

请问你这个是怎么解决的，我也报这个错
