### ISSUE TITLE
完美自定义解决我的需求~！大赞！

### ISSUE THREAD

**Issue by tracyzhao2018** [ferrinweb/voice-input-button2#26]
我老板的需求：
点击录音按钮，播放一段问题的问话（基于百度语音，文字转声音）；语音播报完成后开始语音识别；
如何解决？，如下
1.将作者的插件安装到你项目的components中，然后在你需要调用的页面import及使用作者的自定义组件voice-input-button标签及格式；
2.在作者写的项目voice-input-button.vue中toggle事件里放置this.$emit("buttonClick", e)（方法名字无所谓）;然后在你需要调用的页面给作者的自定义组件加上@buttonClick="buttonClick"；然后你就可以在你页面中触发这个事件来播放语音；注意这里会同时触发mousedown和touchstart；
3.获取播放一段问题的问话的时长定义参数timer，在作者自定义组件voice-input-button标签上写:WaitTime="timer"；然后到作者项目中voice-input-button.vue写props，在start(e) 事件中我们定义setTimeout方法，把props中返回的参数写到setTimeout中；至此实现了：先播放一段问题的问话，然后获取到了这个问话的时长setTimeout后执行了录音功能。
注意事项：
必须把作者的项目打包后才能运行你修改的代码；
build问题：
可能vue版本不一致，打包时报错哦，注意看是否有Vue packages version mismatch的错误提示；
解决方式：重新单独安装提示冲突的模块  比如如上的冲突，重新下载 npm i vue-template-compiler@2.6.10 --save；然后重新打包即可。
每一次修改voice-input-button.vue后都需要打包哦~
鸣谢：
感谢作者的封装，辛勤的劳作。一分耕耘一分收获，希望作者出更多插件，祝愿作者好人一生平安；诸事顺利

**Comment by ferrinweb** [comment]
谢谢你的反馈和鼓励！很高兴自己的工作能帮助到你！
