### ISSUE TITLE
如何获取录音文件，想要上传到阿里云

### ISSUE THREAD

**Issue by zhaoxiaozhao1** [ferrinweb/voice-input-button2#27]
![image](https://user-images.githubusercontent.com/22173910/92080899-d89a1080-edf4-11ea-81a2-41fb234f0882.png)

源码修改应该就是改这边的vue吧。
改完后，重新跑。还是没生效怎么回事啊。大佬

**Comment by zhaoxiaozhao1** [comment]
还有个问题，从哪里拿语音文件呀。我要上传到阿里云

**Comment by zhaoxiaozhao1** [comment]
![image](https://user-images.githubusercontent.com/22173910/92082802-a0480180-edf7-11ea-8622-7be6afd0d1fb.png)

总多个这个所以我想修改去掉它。背景颜色穿rgba(0,0,0,0)也不管用，设置颜色都不sheng生效

**Comment by ferrinweb** [comment]
你的需求是除了语音转文字外，还需要保存录音文件？目前这个组件没有汇总记录和抛出录音数据，因为对于流式接口，音频拿到后就直接发送到讯飞了。
如果需要增加此功能，你需要追踪下 `src/lib/recorder/index.js` 文件中的 `buffer`，并新建一个数组用来保存音频数据。欢迎pr。

**Comment by zhaoxiaozhao1** [comment]
> 您的需求是除了语音转换文字外，还需要保存录音文件？目前这个组件没有汇总记录和投射录音数据，因为对于流式接口，音频拿到后就直接发送到讯飞了。
> 如果需要增加此功能，你需要追踪下`src/lib/recorder/index.js`文件中的`buffer`，并新建一个并存的音频数据。欢迎使用。

好的，我试试看
