### ISSUE TITLE
点击开始后报错 _from is not defined

### ISSUE THREAD

**Issue by zmj1196838666** [ferrinweb/voice-input-button2#3]
![1577871099(1)](https://user-images.githubusercontent.com/44490823/71639975-9ac07780-2cbc-11ea-8b40-a7623d7c79c4.jpg)

**Comment by ferrinweb** [comment]
贴一下具体的报错信息吧。

**Comment by zmj1196838666** [comment]
![1577872071(1)](https://user-images.githubusercontent.com/44490823/71649787-6eecd280-2d4c-11ea-8672-2f87d8dedd20.png)

**Comment by zmj1196838666** [comment]
![1577872071(1)](https://user-images.githubusercontent.com/44490823/71649822-b83d2200-2d4c-11ea-8075-74edfa1e1867.png)

**Comment by zmj1196838666** [comment]
![1577872071(1)](https://user-images.githubusercontent.com/44490823/71649841-d6a31d80-2d4c-11ea-9c80-67cc5800dfb7.png)

**Comment by zmj1196838666** [comment]
[1577933089(1)](https://user-images.githubusercontent.com/44490823/71649853-fa666380-2d4c-11ea-92c7-5d7c85e83efc.jpg)

**Comment by zmj1196838666** [comment]
![1577871099(1)](https://user-images.githubusercontent.com/44490823/71649872-284ba800-2d4d-11ea-84bf-009d85fa0c42.jpg)

**Comment by zmj1196838666** [comment]
![1577933237(1)](https://user-images.githubusercontent.com/44490823/71649881-4913fd80-2d4d-11ea-9fb3-9ab35878ca7a.jpg)

**Comment by ferrinweb** [comment]
我在工程目录没有找到 _from 关键字，你也在你的工程目录下搜索下这个关键字，看是不是误操作修改了变量呢？

**Comment by zmj1196838666** [comment]
![1577946298(1)](https://user-images.githubusercontent.com/44490823/71654264-bfbff380-2d6b-11ea-8d7e-7cdd281e10f3.jpg)
使用的是uni框架，就是兼容到多平台，我们项目要运行到h5和微信小程序，看这个文件应该是编译微信相关的，可能是这里出问题了

**Comment by zmj1196838666** [comment]
使用的是uni框架，就是兼容到多平台，我们项目要运行到h5和微信小程序，看这个文件应该是编译微信相关的，可能是这里出问题了
![1577946717(1)](https://user-images.githubusercontent.com/44490823/71654412-b08d7580-2d6c-11ea-85bc-34dc8deed458.png)

**Comment by ferrinweb** [comment]
抱歉，小程序的话就尽量不推荐使用这个组件了，这个组件是使用 getuserMedia API，听写采用讯飞的接口。小程序端没有 window 对象，缺少各种上下文依赖，建议采用小程序的语音识别扩展。
