### ISSUE TITLE
兼容

### ISSUE THREAD

**Issue by ItAzeY** [ferrinweb/voice-input-button2#30]
老哥你这个不兼容ios和安卓的吧?
还是通过webRTC 中的 navigator.mediaDevices.getUserMedia 么? 
我没看到有弹出 需要点击用户授权语音的 提示,是怎么做到的.

**Comment by ferrinweb** [comment]
首次使用时，安卓和ios需要申请录音权限，浏览器会自动弹出授权申请。如果没有弹出需要检查是否曾经已拒绝。曾经拒绝或由兼容原因未弹出权限请求界面，可以前往权限管理界面进行赋权。

**Comment by Demoxiaozhi** [comment]
老哥，你这个微信浏览器H5貌似无法启用麦克风。网上搜索经验，说的是iOS端微信浏览器没法启用麦克风，是这样的吗。求解答，谢谢了。
