### ISSUE TITLE
iOS端，微信浏览器H5页面无法使用

### ISSUE THREAD

**Issue by Demoxiaozhi** [ferrinweb/voice-input-button2#31]
老哥，你这个微信浏览器H5貌似无法启用麦克风。网上搜索经验，说的是iOS端微信浏览器没法启用麦克风，是这样的吗。求解答，谢谢了。

具体操作：
点击插件的麦克风，微信浏览器提示：
无法录音：未找到录音设备、当前浏览器不支持录音或用户未授权！

**Comment by ferrinweb** [comment]
浏览器内的页面使用录音权限，前提是浏览器本身拥有录音权限。

**Comment by Demoxiaozhi** [comment]
好的，明白了，谢谢！
