### ISSUE TITLE
部署到服务器，使用chrome/安卓浏览器/ios浏览器均报“无法录音”错误，只有当是localhost前缀才可以使用

### ISSUE THREAD

**Issue by janeLLLL** [ferrinweb/voice-input-button2#32]
大佬您好，目前使用您开发的组件，在本地使用chrome测试正常，但是部署到服务器，再使用PC/手机浏览器打开（且确保系统已经打开了录音权限），就会报以下错误：

无法录音：未找到录音设备、当前浏览器不支持录音或用户未授权！

（图片贴不上去…）

不知道是什么问题呢？

**Comment by ferrinweb** [comment]
需要确保使用了 https 协议。

**Comment by janeLLLL** [comment]
> 需要确保使用了 https 协议。

好的，十分感谢！
