### ISSUE TITLE
大哥求微信小程序的例子

### ISSUE THREAD

**Issue by 531431988** [ferrinweb/voice-input-button2#37]
参考这个文档没弄出来，一直报{"code":10043,"message":"audioCoding decode fail","sid":"iat000da283@gz1784dafdba75078802"}

http://bbs.xfyun.cn/forum.php?mod=viewthread&tid=43758&highlight=%E5%BE%AE%E4%BF%A1%2B%E5%B0%8F%E7%A8%8B%E5%BA%8F

大佬写个小程序的例子吧

**Comment by 531431988** [comment]
写个简单调用就行了，不太懂语音格式编码这块，实在搞不定

**Comment by ferrinweb** [comment]
抱歉，对小程序不熟悉，你可参考讯飞相关文档来处理：
- [讯飞/文档中心/语音识别/语音听写/WebAPI文档/错误码](https://www.xfyun.cn/doc/asr/voicedictation/API.html#%E9%94%99%E8%AF%AF%E7%A0%81) 中关于 10043 码的说明
- 你所引用的小程序集成讯飞语音听写文档的第二页，`接⼝数据传输与接收`中第一节关于编码的说明
