### ISSUE TITLE
在windows下没有任何问题，再liunx下提示“无法录音：未找到录音设备、当前浏览器不支持录音或用户未授权！”

### ISSUE THREAD

**Issue by lixiaofeng294** [ferrinweb/voice-input-button2#39]
![image](https://user-images.githubusercontent.com/82141477/113986177-871c9d00-987f-11eb-8d07-de98fda34b9b.png)

**Comment by lixiaofeng294** [comment]
**_### 如果不是https方式的话，可以通过以下方式：_**

      **具体位置，在桌面浏览器快捷键 ---> 属性---> 目标位置 后面追加这段内容**

    **例如：C:\Users\admin\AppData\Local\Google\Chrome\Application\chrome.exe --unsafely-treat-insecure-origin-as-secure="http://改成你的IP:13050/xx/index.html"

     http://改成你的IP:13050/xx/index.html  这点就是你访问服务的地址，相当于放开安全设置**

**Comment by ferrinweb** [comment]
未测试 linux 系统，可能不支持
