### ISSUE TITLE
语音延迟返回问题

### ISSUE THREAD

**Issue by snowlystar** [ferrinweb/voice-input-button2#4]
第一次语音说了很多内容，只返回一部分。第二次还没说话，就又返回了第一次的语音。官网demo没有这个问题，盼修复

**Comment by ferrinweb** [comment]
谢谢反馈，我测试下，尽快修复。@snowlystar

**Comment by snowlystar** [comment]
经过调试，原因为：浏览器语音缓存问题。
需要修改recoreder/index.js文件中的2个地方：
1，buffer缓存变量需要修改为可写
`const buffer = []`
修改为
`let buffer = []`
2、在stop方法里，清空buffer
` if (this.recorder) {
        this.mediaStream.disconnect(this.recorder)`
修改为
` if (this.recorder) {
        **buffer=[]//清空话筒到浏览器的语音缓存**
        this.mediaStream.disconnect(this.recorder)`

**Comment by ferrinweb** [comment]
好的，我检查下，谢谢。

**Comment by ferrinweb** [comment]
该问题已修复，原因是事件流不清晰导致的错误，谢谢你的反馈@snowlystar
