### ISSUE TITLE
vue3

### ISSUE THREAD

**Issue by tonghehui** [ferrinweb/voice-input-button2#50]
有没有vue3的配置方法？ 我vue3的项目使用会报各种错误

**Comment by 54ljd** [comment]
https://blog.csdn.net/m0_58501235/article/details/127900192?spm=1001.2014.3001.5502

**Comment by ferrinweb** [comment]
暂时没有精力开发 vue3 版本，欢迎有精力的朋友 PR.
谢谢 @54ljd 提供的方案.

**Comment by huzw1995** [comment]
> https://blog.csdn.net/m0_58501235/article/details/127900192?spm=1001.2014.3001.5502

顶顶，这样确实可以适配vue3
