### ISSUE TITLE
大佬 我想把这个打包放到服务器上 然后在手机上测试下兼容 但是担保只有js 和map

### ISSUE THREAD

**Issue by mrxuanz** [ferrinweb/voice-input-button2#6]
voice-input-button.js voice-input-button.js.map

**Comment by ferrinweb** [comment]
不太理解你所说的情况，能详细说下吗？

**Comment by mrxuanz** [comment]
非常感谢大神百忙之中的帮助 我打包完成后生成dist目录 目录里面只有一个js文件 和一个map 文件   不知道js怎么部署 本人才疏学浅 以前打包都是有css html 的  我配置webpack总是出错  所以向您请教一下

**Comment by ferrinweb** [comment]
部署这两个文件到http服务器同一个目录即可，使用时将js文件引入到你的文件中，插件依赖 Vue 对象，须提前加载。

**Comment by mrxuanz** [comment]
谢谢您大神 大神也请注意休息  非常感谢您
