### ISSUE TITLE
想问问vue3+ts怎么使用

### ISSUE THREAD

**Issue by mksasx** [ferrinweb/voice-input-button2#66]

**Comment by mksasx** [comment]
![image](https://user-images.githubusercontent.com/35629227/221722193-1e26e9f4-3408-45de-ae4a-5abff35766ae.png)不知道这是怎么回事

**Comment by mksasx** [comment]
![Uploading image.png…]()
像这种是为啥？

**Comment by mksasx** [comment]
像这种是为啥？
![image](https://user-images.githubusercontent.com/35629227/221728504-48dac802-7165-4153-98d0-e0cf2dff4724.png)

**Comment by ferrinweb** [comment]
不支持 vue3 和 ts。欢迎 fork 自行适配或重构
