### ISSUE TITLE
好像兼容不了IE10呢

### ISSUE THREAD

**Issue by splendidTCX** [ferrinweb/voice-input-button2#7]
操作系统:windows10
前端框架: vue

![图片](https://user-images.githubusercontent.com/11351325/81050340-666ef900-8ef2-11ea-97d6-76581ee32df7.png)
麻烦作者有时间看一下，若是还需要提供啥系统信息我再说

**Comment by ferrinweb** [comment]
目前考虑是同源策略导致的，参考：
- [Worker](https://developer.mozilla.org/zh-CN/docs/Web/API/Worker/Worker)
- [浏览器的同源策略](https://developer.mozilla.org/zh-CN/docs/Web/Security/Same-origin_policy)
因为各类别浏览器对 data URIs 的同源策略处理不同。

欢迎提供兼容版本 pr。
