### ISSUE TITLE
密钥直接写在前端文件中不会不安全吗？

### ISSUE THREAD

**Issue by goozi** [ferrinweb/voice-input-button2#73]
我有一个疑问，讯飞的相关密钥都直接写在前端文件中，这样不是暴露了吗？

**Comment by ferrinweb** [comment]
确实不够安全。

如果你需要更高的安全性，可以考虑二次开发。
具体参考这个文件即可：lib/recorder/index.js, line:162

你可以将请求发送到指定的代理服务器，由自架设的服务器托管密钥。
