### ISSUE TITLE
请问大佬，小程序可以用吗？我目前遇到三个问题

### ISSUE THREAD

**Issue by carl-tian** [ferrinweb/voice-input-button2#78]
请问大佬，小程序可以用吗？我目前遇到三个问题

**Comment by carl-tian** [comment]
请问大佬，小程序可以用吗？我目前遇到三个问题

**Comment by carl-tian** [comment]
1.小程序里直接报错，找不到报错代码在哪里，全局没有
![202311061413_35264](https://github.com/ferrinweb/voice-input-button2/assets/68577385/3adff533-cab9-4d29-a769-84f1684fdd47)

**Comment by carl-tian** [comment]
2.本地调试没问题，服务器端没有报错信息，但是却请求不返回数据了，说话无响应，本地localhost是能够语音识别的，服务端域名是https的`
![image](https://github.com/ferrinweb/voice-input-button2/assets/68577385/a2af31c2-4785-41ef-b5bb-6960e2b48ef6)
`

**Comment by carl-tian** [comment]
3.讯飞接口偶先100008等报错，说是请求里头少东西，这个是偶先，最重要的是前两个问题，大佬有空看看

**Comment by ferrinweb** [comment]
本身不直接支持小程序，参考： #3， #37
